from fastapi import FastAPI
from fastapi.responses import StreamingResponse
import asyncio
import json

app = FastAPI()


SUMMARY = (
    "This is a fake summary generated by the test server. "
    "It behaves exactly like Ollama streaming responses. "
    "Each word is streamed individually so that the frontend "
    "can be tested without loading an actual LLM."
)


async def fake_ollama_stream():

    words = SUMMARY.split(" ")

    for word in words:

        packet = {
            "model": "llama3.1:8b-instruct-q4_K_M",
            "created_at": "2026-07-09T12:00:00Z",
            "message": {
                "role": "assistant",
                "content": word + " "
            },
            "done": False
        }

        yield json.dumps(packet) + "\n"

        await asyncio.sleep(0.15)

    yield json.dumps({
        "model": "llama3.1:8b-instruct-q4_K_M",
        "done": True
    }) + "\n"


@app.post("/api/chat")
async def chat():
    return StreamingResponse(
        fake_ollama_stream(),
        media_type="application/x-ndjson"
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=11435)